---
name: Create configMap
on:
  workflow_call:
    inputs:
      NAMESPACE:
        required: true
        type: string
        default: ""
      FILE_NAME:
        required: true
        type: string
        default: ""
      ENVIRONMENT:
        required: true
        type: string
        default: ""
    secrets:
      GKE_SA_KEY:
        required: true
      PROJECT_ID:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Google Cloud
      uses: jusbrasil/data-workflows/.github/actions/setup-gcloud@main
      with:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

    - name: Create configMap
      run: |-
        CM_NAME=$(echo ${{ inputs.FILE_NAME }} | cut -d / -f 4 | cut -f 1 -d '.')-$(echo ${{ inputs.FILE_NAME }} | cut -d / -f 3)-cm

        kubectl create configmap ${CM_NAME} --from-file=${{ inputs.FILE_NAME }} -n ${{ inputs.NAMESPACE }} || \
        kubectl delete configmap ${CM_NAME} -n ${{ inputs.NAMESPACE }} && \
        kubectl create configmap ${CM_NAME} --from-file=${{ inputs.FILE_NAME }} -n ${{ inputs.NAMESPACE }}

      shell: bash
