---
name: Deploy Helmfile
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
        default: ""
      WORKDIR:
        required: false
        type: string
        default: ./
      HELMFILE_NAME:
        required: true
        type: string
        default: ""
    secrets:
      GKE_SA_KEY:
        required: true
      PROJECT_ID:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v0.9.0

    - name: Set up Google Cloud
      uses: jusbrasil/data-workflows/.github/actions/setup-gcloud@main
      with:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

    - name: Deploy Helmfile
      working-directory: ${{ inputs.WORKDIR }}
      run: |-
        helmfile -f ${{ inputs.HELMFILE_NAME }}.yaml -e ${{ inputs.ENVIRONMENT }} sync
      shell: bash
